---
- hosts: dev
  gather_facts: no
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0
        state: present
      become: true
      
    - name: creating a directory
      file:
        path: /tmp/gamefolder
        state: directory

    - name: copy war file 
      copy: 
        src: "{{ workspace }}/gameoflife-0.0.1.war"
        dest: "/tmp/gamefolder/gameoflife-0.0.1.war"
        mode: 0777

    - name: executing war
      shell: "nohup java -jar gameoflife-0.0.1.war &"
      args: 
        chdir: /tmp/gamefolder/
      become: true
